jsonData5 <- jsonData5[,c("data.domain", "data.selftext_html","data.selftext","data.over_18","data.author", "data.score", "data.created_utc","data.title", "data.ups","data.num_comments")]
jsonData5$data.selftext <- as.character.factor(jsonData5$data.selftext)
writeMat("test.mat", A = A, B= B)
#library(R.matlab)
#matFile <- dataset2[,-c(1,2,3,5,6,7,8,9)]

# X <- as.matrix.data.frame(matFile)
#writeMat("X.mat", X = X)
jsonData5$contentLength <- lengthText
jsonData5$contentLength <- unlist(jsonData5$contentLength)
jsonData5$data.title <- as.character.factor(jsonData5$data.title)
lengthTitle <- lapply(jsonData5$data.title, nchar)
jsonData5$titleLength <- lengthTitle
jsonData5$titleLength <- unlist(jsonData5$titleLength)
jsonData5$data.selftext <- unlist(lapply(jsonData5$data.selftext,tolower))

jsonData5$wFunny <- unlist(lapply(jsonData5$data.selftext, countWordInText,"funny"))
jsonData5$wPics<- unlist(lapply(jsonData5$data.selftext, countWordInText,"pics"))

jsonData5$wVideos<- unlist(lapply(jsonData5$data.selftext, countWordInText,"videos"))


jsonData5$wGifs<- unlist(lapply(jsonData5$data.selftext, countWordInText,"gifs"))
jsonData5$wGaming<- unlist(lapply(jsonData5$data.selftext, countWordInText,"gaming"))
jsonData5$wLOL<- unlist(lapply(jsonData5$data.selftext, countWordInText,"lol"))

jsonData5$wWTF<- unlist(lapply(jsonData5$data.selftext, countWordInText,"wtf"))
jsonData5$wNews<- unlist(lapply(jsonData5$data.selftext, countWordInText,"news"))
jsonData5$wPolitics<- unlist(lapply(jsonData5$data.selftext, countWordInText,"politics"))
jsonData5$wMusic<- unlist(lapply(jsonData5$data.selftext, countWordInText,"music"))
jsonData5$wSports<- unlist(lapply(jsonData5$data.selftext, countWordInText,"sports"))
jsonData5$wAnimal<- unlist(lapply(jsonData5$data.selftext, countWordInText,"animal"))
jsonData5$wTechnology<- unlist(lapply(jsonData5$data.selftext, countWordInText,"Technology"))
jsonData5$wFitness<- unlist(lapply(jsonData5$data.selftext, countWordInText,"fitness"))
jsonData5$wTechnology<- unlist(lapply(jsonData5$data.selftext, countWordInText,"technology"))
jsonData5$wJoke<- unlist(lapply(jsonData5$data.selftext, countWordInText,"joke"))
jsonData5$wSex<- unlist(lapply(jsonData5$data.selftext, countWordInText,"sex"))
jsonData5$wTime<- unlist(lapply(jsonData5$data.selftext, countWordInText,"time"))
jsonData5$wFriend<- unlist(lapply(jsonData5$data.selftext, countWordInText,"friend"))


jsonData5$wLove<- unlist(lapply(jsonData5$data.selftext, countWordInText,"love"))
jsonData5$wReddit<- unlist(lapply(jsonData5$data.selftext, countWordInText,"reddit"))
jsonData5$wBlack<- unlist(lapply(jsonData5$data.selftext, countWordInText,"black"))
jsonData5$wWomen<- unlist(lapply(jsonData5$data.selftext, countWordInText,"women"))
jsonData5$wPicture<- unlist(lapply(jsonData5$data.selftext, countWordInText,"picture"))
jsonData5$wGirl<- unlist(lapply(jsonData5$data.selftext, countWordInText,"girl"))
jsonData5$wFuck<- unlist(lapply(jsonData5$data.selftext, countWordInText,"fuck"))
jsonData5$wFavourite<- unlist(lapply(jsonData5$data.selftext, countWordInText,"favourite"))
jsonData5$wdog<- unlist(lapply(jsonData5$data.selftext, countWordInText,"dog"))
jsonData5$whappy<- unlist(lapply(jsonData5$data.selftext, countWordInText,"happy"))
jsonData5$wfeel<- unlist(lapply(jsonData5$data.selftext, countWordInText,"feel"))
jsonData5$wman<- unlist(lapply(jsonData5$data.selftext, countWordInText,"man"))
jsonData5$wobama<- unlist(lapply(jsonData5$data.selftext, countWordInText,"obama"))

jsonData5$wface<- unlist(lapply(jsonData5$data.selftext, countWordInText,"face"))
jsonData5$wcat<- unlist(lapply(jsonData5$data.selftext, countWordInText,"cat"))
jsonData5$wnight<- unlist(lapply(jsonData5$data.selftext, countWordInText,"night"))
jsonData5$wworld<- unlist(lapply(jsonData5$data.selftext, countWordInText,"world"))
jsonData5$wlooking<- unlist(lapply(jsonData5$data.selftext, countWordInText,"looking"))
jsonData5$widea<- unlist(lapply(jsonData5$data.selftext, countWordInText,"idea"))
jsonData5$wpost<- unlist(lapply(jsonData5$data.selftext, countWordInText,"post"))

jsonData5$wX_POST<- unlist(lapply(jsonData5$data.selftext, countWordInText,"x-post"))
jsonData5$wcomments<- unlist(lapply(jsonData5$data.selftext, countWordInText,"comments"))
jsonData5$wsexy<- unlist(lapply(jsonData5$data.selftext, countWordInText,"sexy"))
jsonData5$wgirlfriend<- unlist(lapply(jsonData5$data.selftext, countWordInText,"girlfriend"))

jsonData5$wbeautiful<- unlist(lapply(jsonData5$data.selftext, countWordInText,"beautiful"))
jsonData5$whome<- unlist(lapply(jsonData5$data.selftext, countWordInText,"home"))
jsonData5$wepisode<- unlist(lapply(jsonData5$data.selftext, countWordInText,"episode"))
jsonData5$wday<- unlist(lapply(jsonData5$data.selftext, countWordInText,"day"))
jsonData5$whelp<- unlist(lapply(jsonData5$data.selftext, countWordInText,"help"))
jsonData5$wparty<- unlist(lapply(jsonData5$data.selftext, countWordInText,"party"))
jsonData5$wstop<- unlist(lapply(jsonData5$data.selftext, countWordInText,"stop"))
jsonData5$wrequest<- unlist(lapply(jsonData5$data.selftext, countWordInText,"request"))
jsonData5$wbook<- unlist(lapply(jsonData5$data.selftext, countWordInText,"book"))
jsonData5$wamerican<- unlist(lapply(jsonData5$data.selftext, countWordInText,"american"))

jsonData5$wschool<- unlist(lapply(jsonData5$data.selftext, countWordInText,"school"))
jsonData5$wamazing<- unlist(lapply(jsonData5$data.selftext, countWordInText,"amazing"))
jsonData5$wlife<- unlist(lapply(jsonData5$data.selftext, countWordInText,"life"))
jsonData5$wfavorite<- unlist(lapply(jsonData5$data.selftext, countWordInText,"favorite"))
jsonData5$wwatching<- unlist(lapply(jsonData5$data.selftext, countWordInText,"watching"))
jsonData5$wshit<- unlist(lapply(jsonData5$data.selftext, countWordInText,"shit"))
jsonData5$wbad<- unlist(lapply(jsonData5$data.selftext, countWordInText,"bad"))
jsonData5$wwork<- unlist(lapply(jsonData5$data.selftext, countWordInText,"work"))
jsonData5$wbaby<- unlist(lapply(jsonData5$data.selftext, countWordInText,"baby"))
jsonData5$wthought<- unlist(lapply(jsonData5$data.selftext, countWordInText,"thought"))
jsonData5$wsubreddit<- unlist(lapply(jsonData5$data.selftext, countWordInText,"subreddit"))
jsonData5$wart<- unlist(lapply(jsonData5$data.selftext, countWordInText,"art"))
jsonData5$wkid<- unlist(lapply(jsonData5$data.selftext, countWordInText,"wkid"))
jsonData5$wplay<- unlist(lapply(jsonData5$data.selftext, countWordInText,"wplay"))
jsonData5$wgame<- unlist(lapply(jsonData5$data.selftext, countWordInText,"game"))
jsonData5$wplay<- unlist(lapply(jsonData5$data.selftext, countWordInText,"play"))
jsonData5$wfeel<- unlist(lapply(jsonData5$data.selftext, countWordInText,"feel"))
jsonData5$wpretty<- unlist(lapply(jsonData5$data.selftext, countWordInText,"pretty"))
jsonData5$wmeet<- unlist(lapply(jsonData5$data.selftext, countWordInText,"meet"))

jsonData5$wtry<- unlist(lapply(jsonData5$data.selftext, countWordInText,"try"))
jsonData5$wyoutube<- unlist(lapply(jsonData5$data.selftext, countWordInText,"youtube"))
jsonData5$wass<- unlist(lapply(jsonData5$data.selftext, countWordInText,"ass"))

jsonData5$wfan<- unlist(lapply(jsonData5$data.selftext, countWordInText,"fan"))
jsonData5$wpeople<- unlist(lapply(jsonData5$data.selftext, countWordInText,"people"))
jsonData5$wwife<- unlist(lapply(jsonData5$data.selftext, countWordInText,"wife"))
jsonData5$wfacebook<- unlist(lapply(jsonData5$data.selftext, countWordInText,"facebook"))
jsonData5$wfamily<- unlist(lapply(jsonData5$data.selftext, countWordInText,"family"))
jsonData5$wmorning<- unlist(lapply(jsonData5$data.selftext, countWordInText,"morning"))
jsonData5$wcity<- unlist(lapply(jsonData5$data.selftext, countWordInText,"city"))
jsonData5$wspoilers<- unlist(lapply(jsonData5$data.selftext, countWordInText,"spoilers"))